"""initial schema

Revision ID: 6d2aff03ddb0
Revises: 
Create Date: 2026-08-25 11:01:45.933940

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6d2aff03ddb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.String(length=4), nullable=False),
    sa.Column('competition', sa.String(length=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('home_team', sa.String(length=64), nullable=False),
    sa.Column('away_team', sa.String(length=64), nullable=False),
    sa.Column('fthg', sa.Integer(), nullable=False),
    sa.Column('ftag', sa.Integer(), nullable=False),
    sa.Column('ftr', sa.String(length=1), nullable=False),
    sa.Column('hthg', sa.Integer(), nullable=True),
    sa.Column('htag', sa.Integer(), nullable=True),
    sa.Column('htr', sa.String(length=1), nullable=True),
    sa.Column('referee', sa.String(length=64), nullable=True),
    sa.Column('home_xg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('away_xg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_code', 'date', 'home_team', 'away_team', name='uq_match_natural_key')
    )
    op.create_table('odds_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('selection', sa.String(length=10), nullable=False),
    sa.Column('line', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'bookmaker', 'market', 'phase', 'selection', 'line', name='uq_odds_natural_key', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds_quote')
    op.drop_table('match')
    # ### end Alembic commands ###