"""add staging tables

Revision ID: f6a9a3e1ed39
Revises: 6d2aff03ddb0
Create Date: 2026-08-25 16:15:48.611321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a9a3e1ed39'
down_revision = '6d2aff03ddb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.String(length=4), nullable=False),
    sa.Column('competition', sa.String(length=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('home_team', sa.String(length=64), nullable=False),
    sa.Column('away_team', sa.String(length=64), nullable=False),
    sa.Column('fthg', sa.Integer(), nullable=True),
    sa.Column('ftag', sa.Integer(), nullable=True),
    sa.Column('ftr', sa.String(length=1), nullable=True),
    sa.Column('hthg', sa.Integer(), nullable=True),
    sa.Column('htag', sa.Integer(), nullable=True),
    sa.Column('htr', sa.String(length=1), nullable=True),
    sa.Column('referee', sa.String(length=64), nullable=True),
    sa.Column('home_xg', sa.Numeric(precision=4, scale=2, asdecimal=False), nullable=True),
    sa.Column('away_xg', sa.Numeric(precision=4, scale=2, asdecimal=False), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_quote_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_code', sa.String(length=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=64), nullable=False),
    sa.Column('away_team', sa.String(length=64), nullable=False),
    sa.Column('bookmaker', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('selection', sa.String(length=10), nullable=True),
    sa.Column('line', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds_quote_staging')
    op.drop_table('match_staging')
    # ### end Alembic commands ###